### PR TITLE
Rfc2812: parse IRC messages in more details

### PR DESCRIPTION
**Pull request by c-cube**
The API is still a bit rough, but better than before imho (common messages are represented explicitely
as variants).

### CODE REVIEW

**Comment by johnelse** [comment]
Please could you rebase this against master? Would be nice to get rid of the merge commit :)

Also I don't think the opam file change is needed - there's on in master now, and it looks like the change is what's breaking the travis build.

Thanks!

**Comment by c-cube** [comment]
Aww, rebasing in this case is going to be tough... Is the merge commit that annoying? :p

**Comment by c-cube** [comment]
About the opam file: `ounit` should be an optional dependency, which means that the travis script must install `ounit` explicitely before running tests.

**Comment by johnelse** [comment]
I haven't tried it, but it looks like you can mark opam dependencies as being only required for tests, [for example](https://github.com/mirage/ocaml-cohttp/blob/88013ea80bea40c20f18b4ae585517787c3b810f/opam#L44).

**Comment by c-cube** [comment]
How are things going wrt this PR? :)

**Comment by johnelse** [comment]
Sorry, I've been flat out with work the past couple of weeks :(

I'll check it out.

**Comment by johnelse** [comment]
Functionality-wise this looks OK, although the change history could be simplified. Also the travis build is still broken - do you really need the change to the OPAM file?

**Comment by c-cube** [comment]
Ok, I'll rebase. About the opam file: I don't understand exactly how travis works, so I don't know how to specify either

1. how to `--disable-tests`
2. how to install ounit before running tests

**Comment by johnelse** [comment]
As-is, `make` builds the tests, but they don't get run until you `make test`, so ounit is a required dependency at the moment.

I thought adding `{test}` to the opam file would mean that ounit automatically gets installed when the `build-test` section is run, but that doesn't seem to be happening - not sure why.

**Comment by c-cube** [comment]
That's weird. I find it annoying when packages require `ounit` even if I don't run their tests; here, the main build path should probably not `--enable-tests` nor build them, what do you think?

**Comment by c-cube** [comment]
Hope the splitting fits you better

**Comment by johnelse** [comment]
Looks good! Thanks for the rebase.

I'm happy to have ounit as an optional dependency if we can get it to work with opam/travis :)

**Comment by johnelse** [comment]
It builds...merging now. Thanks!

**Pull request merged**
