### PR TITLE
Add optional quit message for send_quit

### PR DESCRIPTION
**Pull request by FardaleM**
Also fix test

### CODE REVIEW

**Comment by FardaleM** [comment]
This break will break existing code because there is no positional argument to send_quit.

**Comment by johnelse** [comment]
Hey, thanks for the merge request!

I think since this breaks backwards compatibility anyway, I'd like to add an extra `unit` argument to `send_quit` so the caller can avoid specifying ` msg`. This is already the case in the other methods that use optional arguments.

```
val send_quit : ?msg:string -> connection:connection_t -> unit -> unit Io.t
```

Cheers!

**Comment by FardaleM** [comment]
OK, I made the modification.

**Comment by johnelse** [comment]
Thanks!

**Pull request merged**
