### PR TITLE
add `logs` and basic SASL authentication

### LINKED ISSUE #56: proposal: use `logs`
it's the de facto standard these days, and it'd give us more visibility into  what happens. A custom source just for irc-client would be helpful. I can do this if you're ok with it @johnelse

### PR DESCRIPTION
**Pull request by c-cube**
close #56 and allows bots to log into irc.libera.chat from some servers (e.g. on digital ocean).

### CODE REVIEW

**Comment by johnelse** [comment]
Looks good! Could you add `base64` to `irc-cilent.opam`? That should get the CI passing.

**Comment by c-cube** [comment]
idk why it still fails :/. Seems like parts of it is a too old version of openssl?

**Comment by johnelse** [comment]
> idk why it still fails :/. Seems like parts of it is a too old version of openssl?

Yeah I think so. I'll merge and fix things up, the code changes look fine - I should really migrate the CI to travis.com or github actions anyway.

**Comment by johnelse** [comment]
Using a newer Ubuntu version for the docker container fixed it :D

**Comment by johnelse** [comment]
Thanks, btw :) I'll turn this into a release at the weekend.

**Pull request merged**
